/*
 * ACPHY Core module internal interface holding tbl id's
 *
 * Copyright 2018 Broadcom
 *
 * This program is the proprietary software of Broadcom and/or
 * its licensors, and may only be used, duplicated, modified or distributed
 * pursuant to the terms and conditions of a separate, written license
 * agreement executed between you and Broadcom (an "Authorized License").
 * Except as set forth in an Authorized License, Broadcom grants no license
 * (express or implied), right to use, or waiver of any kind with respect to
 * the Software, and Broadcom expressly reserves all rights in and to the
 * Software and all intellectual property rights therein.  IF YOU HAVE NO
 * AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY
 * WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF
 * THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof, and to
 * use this information only in connection with your use of Broadcom
 * integrated circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR
 * OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL,
 * SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR
 * IN ANY WAY RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN
 * IF BROADCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii)
 * ANY AMOUNT IN EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF
 * OR U.S. $1, WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY
 * NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * <<Broadcom-WL-IPTag/Proprietary:>>
 *
 * $Id: phy_ac_tblid.h 764806 2018-06-04 23:04:30Z $
 */

#ifndef _phy_ac_tblid_h_
#define _phy_ac_tblid_h_

/* ACPHY tables */
#define ACPHY_TBL_ID_MCS				1
#define ACPHY_TBL_ID_TXEVMTBL				2
#define ACPHY_TBL_ID_NVNOISESHAPINGTBL			3
#define ACPHY_TBL_ID_NVRXEVMSHAPINGTBL			4
#define ACPHY_TBL_ID_PHASETRACKTBL			5
#define ACPHY_TBL_ID_SQTHRESHOLD			6
#define ACPHY_TBL_ID_RFSEQ				7
#define ACPHY_TBL_ID_RFSEQEXT				8
#define ACPHY_TBL_ID_ANTSWCTRLLUT			9
#define ACPHY_TBL_ID_FEMCTRLLUT				10
#define ACPHY_TBL_ID_GAINLIMIT				11
#define ACPHY_TBL_ID_PHASETRACKTBL_B		11
#define ACPHY_TBL_ID_IQLOCAL				12
#define ACPHY_TBL_ID_IQLOCAL0				12
#define ACPHY_TBL_ID_IQLOCALTBL0			12
#define ACPHY_TBL_ID_PAPR				13
#define ACPHY_TBL_ID_SAMPLEPLAY				14
#define ACPHY_TBL_ID_DUPSTRNTBL				15
#define ACPHY_TBL_ID_BFMUSERINDEX			16
#define ACPHY_TBL_ID_BFECONFIG				17
#define ACPHY_TBL_ID_BFEMATRIX				18
#define ACPHY_TBL_ID_FASTCHSWITCH			19
#define ACPHY_TBL_ID_RFSEQBUNDLE			20
#define ACPHY_TBL_ID_LNAROUT				21
#define ACPHY_TBL_ID_LNAROUTLUT				21
#define ACPHY_TBL_ID_MCDSNRVAL				22
#define ACPHY_TBL_ID_BFRRPT				23
#define ACPHY_TBL_ID_BFERPT				24
#define ACPHY_TBL_ID_NVADJTBL				25
#define ACPHY_TBL_ID_PHASETRACKTBL_1X1			26
#define ACPHY_TBL_ID_SCD_DBMTBL				27
#define ACPHY_TBL_ID_DCD_DBMTBL				28
#define ACPHY_TBL_ID_SLNAGAIN				29
#define ACPHY_TBL_ID_BFECONFIG2X2TBL			30
#define ACPHY_TBL_ID_SLNAGAINBTEXTLNA			31
#define ACPHY_TBL_ID_GAINCTRLBBMULTLUTS			32
#define ACPHY_TBL_ID_ESTPWRSHFTLUTS			33
#define ACPHY_TBL_ID_CHANNELSMOOTHING_1x1		34
#define ACPHY_TBL_ID_SGIADJUST				35
#define ACPHY_TBL_ID_SGIADJUSTTBL			35
#define ACPHY_TBL_ID_SLNAGAINTR				36
#define ACPHY_TBL_ID_SLNAGAINEXTLNATR			37
#define ACPHY_TBL_ID_SLNACLIPSTAGETOTGAIN		38
#define ACPHY_TBL_ID_VASIPREGISTERS			41
#define ACPHY_TBL_ID_IQLOCAL1				44
#define ACPHY_TBL_ID_SMCPMTBL			        47
#define ACPHY_TBL_ID_BFDINDEXLUT			63
#define ACPHY_TBL_ID_ESTPWRLUTS0			64
#define ACPHY_TBL_ID_IQCOEFFLUTS0			65
#define ACPHY_TBL_ID_LOFTCOEFFLUTS0			66
#define ACPHY_TBL_ID_RFPWRLUTS0				67
#define ACPHY_TBL_ID_GAIN0				68
#define ACPHY_TBL_ID_GAINBITS0				69
#define ACPHY_TBL_ID_RSSICLIPGAIN0			70
#define ACPHY_TBL_ID_EPSILON0				71
#define ACPHY_TBL_ID_EPSILONTABLE0			71
#define ACPHY_TBL_ID_SCALAR0				72
#define ACPHY_TBL_ID_SCALARTABLE0			72
#define ACPHY_TBL_ID_CORE0CHANESTTBL			73
#define ACPHY_TBL_ID_RSSICLIP2GAIN0			76
#define ACPHY_TBL_ID_CORE0CHANSMTH_CHAN			78
#define ACPHY_TBL_ID_CORE0CHANSMTH_FLTR			79
#define ACPHY_TBL_ID_SNOOPAGC				80
#define ACPHY_TBL_ID_SNOOPPEAK				81
#define ACPHY_TBL_ID_SNOOPCCKLMS			82
#define ACPHY_TBL_ID_SNOOPLMS				83
#define ACPHY_TBL_ID_SNOOPDCCMP				84
#define ACPHY_TBL_ID_BBPDEPSILON_I0			86
#define ACPHY_TBL_ID_BBPDEPSILON_Q0			87
#define ACPHY_TBL_ID_FDSS_MCSINFOTBL0			88
#define ACPHY_TBL_ID_FDSS_SCALEADJUSTFACTORSTBL0	89
#define ACPHY_TBL_ID_FDSS_BREAKPOINTSTBL0		90
#define ACPHY_TBL_ID_FDSS_SCALEFACTORSTBL0		91
#define ACPHY_TBL_ID_FDSS_SCALEFACTORSDELTATBL0		92
#define ACPHY_TBL_ID_PAPDLUTSELECT0			93
#define ACPHY_TBL_ID_GAINLIMIT0				94
#define ACPHY_TBL_ID_TXGAINCTRLBBMULTLUTS0		95
#define ACPHY_TBL_ID_ESTPWRLUTS1			96
#define ACPHY_TBL_ID_IQCOEFFLUTS1			97
#define ACPHY_TBL_ID_LOFTCOEFFLUTS1			98
#define ACPHY_TBL_ID_RFPWRLUTS1				99
#define ACPHY_TBL_ID_GAIN1				100
#define ACPHY_TBL_ID_GAINBITS1				101
#define ACPHY_TBL_ID_RSSICLIPGAIN1			102
#define ACPHY_TBL_ID_EPSILON1				103
#define ACPHY_TBL_ID_SCALAR1				104
#define ACPHY_TBL_ID_CORE1CHANESTTBL			105
#define ACPHY_TBL_ID_CORE1CHANSMTH_CHAN			110
#define ACPHY_TBL_ID_CORE1CHANSMTH_FLTR			111
#define ACPHY_TBL_ID_BBPDEPSILON_I1			118
#define ACPHY_TBL_ID_BBPDEPSILON_Q1			119
#define ACPHY_TBL_ID_PAPDLUTSELECT1			125
#define ACPHY_TBL_ID_GAINLIMIT1				126
#define ACPHY_TBL_ID_TXGAINCTRLBBMULTLUTS1		127
#define ACPHY_TBL_ID_DCOE_TABLE0			130
#define ACPHY_TBL_ID_IDAC_TABLE0			131
#define ACPHY_TBL_ID_IDAC_GMAP_TABLE0			132
#define ACPHY_TBL_ID_IDAC_GMAP0				132
#define ACPHY_TBL_ID_ET_SHAPING_LUT			137
#define ACPHY_TBL_ID_ETMFTABLE0				137
#define ACPHY_TBL_ID_WBCAL_PTBL0			140
#define ACPHY_TBL_ID_WBCAL_TXDELAY_BUF0			144
#define ACPHY_TBL_ID_MCLPAGCCLIP2TBL0			127
#define ACPHY_TBL_ID_MCLPAGCCLIP2TBL1			159

/* ******************************************************** */

/* Table IDs 128 and 129 have conflicting table names
 *
 * for 4349:
 * ID 128 -- ACPHY_TBL_ID_GAINCTRLBBMULTLUTS0
 * ID 129 -- ACPHY_TBL_ID_ESTPWRSHFTLUTS0
 *
 * for other chips:
 * ID 128 -- ACPHY_TBL_ID_ESTPWRLUTS2
 * ID 129 -- ACPHY_TBL_ID_IQCOEFFLUTS2
 *
 * This is handled by appropriately conditioning the code
 * with major and minor revs
 */
#define ACPHY_TBL_ID_ESTPWRLUTS2			128
#define ACPHY_TBL_ID_IQCOEFFLUTS2			129
#define ACPHY_TBL_ID_GAINCTRLBBMULTLUTS0		128
#define ACPHY_TBL_ID_ESTPWRSHFTLUTS0			129

/* ******************************************************** */

#define ACPHY_TBL_ID_LOFTCOEFFLUTS2			130
#define ACPHY_TBL_ID_RFPWRLUTS2				131
#define ACPHY_TBL_ID_GAIN2				132
#define ACPHY_TBL_ID_GAINBITS2				133
#define ACPHY_TBL_ID_RSSICLIPGAIN2			134
#define ACPHY_TBL_ID_EPSILON2				135
#define ACPHY_TBL_ID_SCALAR2				136
#define ACPHY_TBL_ID_CORE2CHANESTTBL			137
#define ACPHY_TBL_ID_DYNRADIOREGTBL1			147
#define ACPHY_TBL_ID_ADCSAMPCAP_PATH1			148
#define ACPHY_TBL_ID_GAINLIMIT2				158
#define ACPHY_TBL_ID_TXGAINCTRLBBMULTLUTS2		159
#define ACPHY_TBL_ID_GAINCTRLBBMULTLUTS1		160
#define ACPHY_TBL_ID_ESTPWRSHFTLUTS1			161
#define ACPHY_TBL_ID_IBFERPTADDRLUT			231

#define ACPHY_TBL_ID_ESTPWRLUTS(core)	\
	(((core == 0) ? ACPHY_TBL_ID_ESTPWRLUTS0 : \
	((core == 1) ? ACPHY_TBL_ID_ESTPWRLUTS1 : \
	((core == 2) ? ACPHY_TBL_ID_ESTPWRLUTS2 : ACPHY_TBL_ID_ESTPWRLUTS3))))

#define ACPHY_TBL_ID_CHANEST(core)	\
	(((core == 0) ? ACPHY_TBL_ID_CORE0CHANESTTBL : \
	((core == 1) ? ACPHY_TBL_ID_CORE1CHANESTTBL : \
	((core == 2) ? ACPHY_TBL_ID_CORE2CHANESTTBL : ACPHY_TBL_ID_CORE3CHANESTTBL))))

#endif /* _phy_ac_tblid_h_ */
